sudo: false

language: python
python: 2.7

cache: pip

script:
  - pip install -r requirements.txt

deploy:
  provider: pypi
  user: colinwren
  password: $PYPI_PASSWORD
  on:
    tags: true
    python: 2.7
